### ISSUE TITLE
Bug when dropping dragged events landing across a midnight boundary

### ISSUE THREAD

**Issue by gwillen** [imightbeamy/gcal-multical-event-merge#15]
When I have the extension active, if I drag a calendar event, and drop it such that it spans midnight -- that is, so that it starts on on day, and ends on a different day -- the calendar UI locks up. (This happens very frequently but not every single time.) I end up with a copy of the event attached to my mouse pointer, as though I'm still dragging it, and I can't drop it, and no other functions work until I reload.

I am running 1.3.4 from the chrome web store. 

I also filed this issue in the web store interface.

Thanks for this extension! I have been promoting it heavily in a certain community I hang out in, in which the popularity of Google Calendar for scheduling personal events has risen to a running gag. Inevitably the people I show it to have the same reaction I did, which is "WHOOOA, HOLY SHIT." :+1:

**Comment by imightbeamy** [comment]
I can reproduce, and whoa, that is some totally crazy behavior. I have no idea where that's coming from but I'll try to take a look soon!

**Comment by imightbeamy** [comment]
The fix for this is published on the web store now! It will roll out over the next couple hours, let me know if you're still seeing this happen!

**Comment by Shtutnik** [comment]
Hi, I think you also need to add this line:
$(this).parent().css('width','0px');

right before or after this line:
$(this).parent().css('visibility','hidden');

in your commit. 

This is because even when the event is hidden, for some reason the calendar seems to add icons to where they are supposed to be. For example, if you have an event which you haven't responded to yet, an arrow will show up, even if you hide the event. By adding the 0 width, the whole div gets shrunk and any icons added to it later won't show up.

Also, another problem with hiding and not removing is that if the event is the whole day then the top bar will contain spaces where the event used to be.

Is this correct? This is the behavior I am seeing..

I'll let you know if I come up with some kind of idea for this..

**Comment by imightbeamy** [comment]
@Shtutnik I'm not seeing any issues with reply/maybe icons. Could you include a screenshot of what you're seeing? Thanks!

**Comment by Shtutnik** [comment]
Sure!
![image](https://cloud.githubusercontent.com/assets/11493106/14439538/41807de0-0034-11e6-82dd-145fcba66d4f.png)

**Comment by gwillen** [comment]
Yeah I'm seeing the same thing Shutunik is with the 'needs reply' arrow now showing up in multiple copies, one per copy of the event. In the source, it is spelled:

<i class="cic cic-nr" title="Not yet responded">&nbsp;</i>

And the selector .cic.cic-nr has visibility:visible set, which is overriding your hide.

I can also confirm that if you set both the width and the height of the hidden element to 0, this seems to fix both issues (the extra floating icons, and the extra space in the 'all day' bar.) Of course, I can't tell if this also rebreaks the drag issue, because I don't actually know what was causing that...

Honestly it might be worth just backing the patch out and rebreaking drag to fix this, though. In a crowded calendar with a lot of 'needs reply' icons, e.g. a work environment, it definitely looks funky now. See e.g.:

<img width="57" alt="screen shot 2016-04-26 at 11 44 47 pm" src="https://cloud.githubusercontent.com/assets/458997/14843963/f7f21428-0c08-11e6-9b47-0e147a21cd62.png">
<img width="133" alt="screen shot 2016-04-26 at 11 44 28 pm" src="https://cloud.githubusercontent.com/assets/458997/14843964/f7f90954-0c08-11e6-81ac-90d5a36a2dd1.png">

**Comment by imightbeamy** [comment]
Hi all,

Sorry for the slow response. I am seeing this to and will fix as soon as I have some time. I know it's really annoying!
