### ISSUE TITLE
Flexibility on event title matching (feature request)

### ISSUE THREAD

**Issue by gwillen** [imightbeamy/gcal-multical-event-merge#16]
While I'm here, a feature request: It would be great it it were possible to make the title matching slightly looser, as an option. One example of this would be ignoring parentheticals at the ends of titles, for that one lab that messes things up. Another example: I would love to see the Facebook and Google Contacts birthday events be mergeable with each other. The former are titled "Name's Birthday", whereas the latter are titled "[cake]Name's birthday", where "[cake]" is an emoji of a slice of cake. So ignoring case and stripping out non-ASCII would make these merge.

I also feel like I see problems with events not merging when participants differ on whether they have accepted/rejected/maybe'd the event. I don't have the exact details figured out, but I assume some state gets wedged into the title in such cases, perhaps invisibly, that could be filtered to make the events merge successfully. It looks like maybe if someone says 'no', strikethrough gets added to the title field which inhibits the merge.

As a final "nice to have", I'd love to see an option to make events titled 'busy' (from coworkers who are not sharing their calendar details) get merged/removed, when there's another event at exactly the same time, on the assumption that it's actually the same event. (Ideally it would be possible to do this only if the busy person is listed on the other event, but I bet you can't do that because it would require more information than the extension has available.)

Thanks for the awesome extension!

**Comment by imightbeamy** [comment]
Thanks for the suggestions! People have asked for fuzzy match before, but I hadn't had time to think about the right way to do it. Removing non non-ASCII would probablly be a good place to start. And maybe only remove parenthetical emails to target that lab specifically.

I'm not sure a fan of merging/removing "busy" events. Hour-long meetings on the hour, and other similar time-slots are common enough that without checking if the person is attending I would want to assume.

In general, I want to be careful not to overzealously merge. When you see one that's not merged you at least know that it's because you're using a hacky extensions vs an event just being totally missing and you being none the wiser.

**Comment by gwillen** [comment]
Yeah I agree about overzealous merging. I mentioned 'busy' because it's a pain point for me, and since 'busy' events contain almost no useful information, it seemed like a very small loss to accidentally kill one wrongly (while still indicating that the person is busy, but mis-indicating what they're doing.) But I definitely would not advocate doing this by default.

**Comment by imightbeamy** [comment]
This is published on the web store now! It will roll out over the next couple hours.

**Comment by gwillen** [comment]
Thank you! :-) I look forward to trying it out.

**Comment by ericbimpex** [comment]
Unfortunately, in an effort to eliminate a cake emoji, you've rendered this otherwise invaluable extension completely useless to most non-ASCII using countries... Clearly unrelated events like: '休み' (ie. vacation) and '東京出張' (ie. business trip to Tokyo) are being merged... We have been happy users here in Japan until recently, but because of this change, will have to turn it off for now.

Please instead consider a blacklist of emoji that needs to be filtered, or at least a way to switch off the filtering of non-ASCII chars.

Otherwise, really great work and thank you!

**Comment by HCAWN** [comment]
@ericbimpex was your last request ever addressed? I'm working on a fork of this extension and if you'd like to file an issue I can make this a toggle
https://github.com/hcawn/gcal-multical-event-merge/issues
H
