### ISSUE TITLE
Events are not merged when you're the event owner 

### ISSUE THREAD

**Issue by Nirazul** [imightbeamy/gcal-multical-event-merge#55]
First of all thank you very much for making the extension available again for the new Gcal!

I've noticed a small bug in Chrome (probably all browsers). When I've set a notification in my own event (alarm) the event is not being merged with the one of others. Maybe there's a way to just ignore notifications (or merge them as they only occur in my own calendars)?

**Comment by imightbeamy** [comment]
I'll take a look! I'm sure we can ignore the alarm. 

Can you add a screenshot what you're seeing?

**Comment by Nirazul** [comment]
Of course!

![dreipol_gmbh_ _calendar_-_week_of_19_february_2018](https://user-images.githubusercontent.com/781476/36355468-e62d1810-14e3-11e8-8259-8240712746b9.jpg)

**Comment by imightbeamy** [comment]
I'm not able to reproduce this with one event having an alarm. In the screenshot below the purple event has an alarm and the green one does not:
![screen shot 2018-02-19 at 9 22 57 am](https://user-images.githubusercontent.com/1229145/36382332-8481dc68-1556-11e8-9571-10727b5c98a6.png)

Is it possible one has a location set and the others don't like the yellow event?

If it doesn't seem like location is the issue, could you screenshot the same set of events with the extension disabled?

**Comment by Nirazul** [comment]
@imightbeamy 
Both have the same location set:

![dreipol_gmbh_ _calendar_-_week_of_19_march_2018_](https://user-images.githubusercontent.com/781476/36385593-36d0b5ce-1593-11e8-846f-7f64603f4b96.jpg)

The only difference I can spot is that one belongs to me and the other two are the entries of my coworkers for the same event, these are being merged correctly.
I guess on my event, there's some extra info that distinguishes from other calendars.

**Comment by tiagonogueira21** [comment]
Same here!

When i'm the organizer it doesn't merge, but if i'm not, it works just fine.

![captura de ecra 2018-02-20 as 16 14 25](https://user-images.githubusercontent.com/33348716/36435474-aa2b27b8-1659-11e8-83cd-69de548579a2.png)
![captura de ecra 2018-02-20 as 16 15 25](https://user-images.githubusercontent.com/33348716/36435485-b3d73522-1659-11e8-9086-58061dd0f935.png)

**Comment by Hadriel** [comment]
I'm seeing it happens to the event but for the calendar where it is the event. Usually when you create an even you put it on your calendar but I tried creating one myself on other calendar I have access and I see that behavior.

I think is because how it choose the eventTitleEls 
`const eventTitleEls = event.querySelectorAll('[aria-hidden="true"]'); `

Looks like those event have another div with aria-hidden="true". 
Could it be that those are been excluded from the eventSets?

**Comment by imightbeamy** [comment]
I'm seeing this now! Realized I wasn't before because I already had a fix locally :) 

[I _think_ this fixes it](https://github.com/imightbeamy/gcal-multical-event-merge/commit/cc0637e2bc976f141e7dfbc06ed35975543e3d05) and I've uploading a new release with that change.

You should get the update over a few hours. If you're in a hurry, you can go to `chrome://extensions/`, check "Developer Mode" and click "Update extensions now":
![screen shot 2018-02-18 at 9 06 49 am](https://user-images.githubusercontent.com/1229145/36352722-48a7320e-148b-11e8-8fcb-ab1f7f3ef7f9.png)

**Comment by Nirazul** [comment]
Confirmed, it works! Thank you very much :)

**Comment by MeganLBrown23** [comment]
Can't RSVP to a calendar event in the new Google Calendar when my Event Merge extension is enabled.  When I disable it, I am able to RSVP.

**Comment by imightbeamy** [comment]
@MeganLBrown23 Can you open a new issue for that? Thanks!
