### ISSUE TITLE
Candy striping is visually jarring so use vertical bars (1/cal) design instead

### ISSUE THREAD

**Issue by AndreasTuranski** [imightbeamy/gcal-multical-event-merge#69]
The coloring scheme makes these entries DRAMATICALLY stand out (like my capitalization there did) when these events are no more important than others. The current "candy striping" scheme is jarring to the visual system which stronging notices repeated diagonal bars as they don't occur in nature normally whereas vertical or horizontal ones do (note automotive alerting painting on emergency vehicles often use diagonal stripes to get attention).
Instead of "candy striping" which is very visually jarring, just split the calendar bar into vertical segments, one for the color of each calendar that has it. This could/should be the new default and an extension option could give the candy stripe treatment if someone wanted it. Thus if the event was in 2 calendars, the left half would be one color and the right half another color, if in 3 calendars, the left third would be one color, the middle section another color, and the right third would be another color. This would be much less visually jarring.

**Comment by GarethLewin** [comment]
This isn’t a bad idea. But as a long time user of this extension that really likes the candy stripes please don’t change the default.

**Comment by imightbeamy** [comment]
Since this extension is completely free and was originally created to scratch a personal itch, I view this as a personal project I kindly share with the world ❤️And I like the stripes! They're fun and silly and look like fruit stipe gum from when I was a kid:
![image](https://user-images.githubusercontent.com/1229145/51627544-70910200-1f10-11e9-9148-4dca8f31412a.png)

I've also avoided added settings and options to this extension for a long time because, quite frankly, I don't have any interest in maintaining the (even minimal) extra complexity. And folks who offer to help maintain always fade away eventually, leaving me with the responsibility.

Here's to hoping Google eventually implements this as a real feature some day! 🤞

**Comment by nirazul** [comment]
These candy stripes are basically the only thing evoking positive emotions when thinking of attending meetings. Please keep it! 😬
