### ISSUE TITLE
Extension breaks 'Find A Time' feature

### ISSUE THREAD

**Issue by tristans** [imightbeamy/gcal-multical-event-merge#7]
Repro steps:
0) Have calendar extension enabled
1) Create a new event
2) Click Find A Time tab
3) Click on the calendar view to select a time

Note that the entire UI is completely unresponsive. It just dies - the only way to continue using Google Calendar is to reload. Disabling the extension results in the UI remaining functional for the meeting creation process.

**Comment by imightbeamy** [comment]
Fix pushed, will update web store shortly.

**Comment by tristans** [comment]
A+++++

**Comment by abackstrom** [comment]
This seems to be broken in v1.3.3. Tristan's original steps trigger the bug.

**Comment by imightbeamy** [comment]
Womp womp, thanks for the heads up. I'll try to get this fixed again soon!

**Comment by abackstrom** [comment]
Hey @imightbeamy, I'm looking at this code right now. What's the expected behavior on the "Find Time" display? Should the extension merge the events into the first calendar column, and remove from all others?

**Comment by imightbeamy** [comment]
Made a few more updates that I *think* actually fixes this now. I'll be updating it on the web store later today and it takes a few hours to roll out so let me know if you're still seeing problems with this tomorrow or Tuesday.

**Comment by Shtutnik** [comment]
I am adding this comment here as well (as issue #15), since I it is relevant for the commit and I am not sure whether it is relevant for both issues.. 

Hi, I think you also need to add this line:
$(this).parent().css('width','0px');

right before or after this line:
$(this).parent().css('visibility','hidden');

in your commit.

This is because even when the event is hidden, for some reason the calendar seems to add icons to where they are supposed to be. For example, if you have an event which you haven't responded to yet, an arrow will show up, even if you hide the event. By adding the 0 width, the whole div gets shrunk and any icons added to it later won't show up.

Also, another problem with hiding and not removing is that if the event is the whole day then the top bar will contain spaces where the event used to be.

Is this correct? This is the behavior I am seeing..

I'll let you know if I come up with some kind of idea for this..
