### ISSUE TITLE
Events Hidden when identical titles on the same time slot

### ISSUE THREAD

**Issue by Llamamib** [imightbeamy/gcal-multical-event-merge#70]
When multiple events with the same title (but different notes) are on the same time slot, only one merges and appears. The other ones are hidden. 

When I deactivate Event merge plugin(chrome), I see both events.
When I activate Event merge plugin(chrome), I only see one of the similar looking events. 

Version 2.1.3
Google Chrome Version 72.0.3626.81 (Build official) (64 bits)
MacOs 10.14.3

**Comment by imightbeamy** [comment]
Sorry to say that this is a feature, not a bug. The only way the extension knows if an event is the "same" is by the title, so if two events are at the same time, with the same title, it considers them the same and merges them.

**Comment by Llamamib** [comment]
Thank you for this answer. 
I don't mind so much that the two events are merged, my problem, however, is that only one of the two events' comment section is displayed. 

Isn't there a way to merge the comments as well? 

Thanks a lot for the good work. :)

**Comment by aurosharman** [comment]
Llamamib, you're not thinking about this from the level of the actual display elements.  The plugin is not editing the content of events.  It just rearranges some code that represents display boxes.

When two events are merged in the calendar display, one of the things that happens is that the code picks one instance of the merged event to be the one whose link it will offer when you click.  If for some reason you need to get into multiple copies, you just need to click the icon for the plugin to turn it off temporarily.

That said, the way you could get the result you want, is that the box that pops up when you click on an event could be edited so instead of being the original info box for one version of the event, it offers links to the different versions.  That would be a pretty significant new feature though, since at present there's no code targeting that part of the interface at all, AFAICT.

**Comment by aurosharman** [comment]
I think in theory the actual GCal team could implement a feature like this that was more intelligent about understanding which instances of multiple boxes in your interface actually represent "the same event", because they have access to the underlying database, with full info about where the event originated, who was invited, etc.  They could merge things in the display, even if individual users have customized their local titles, notes, etc.  All this widget has is the content that's visible in the interface.  And it works pretty great, given what it has to go on.

**Comment by HCAWN** [comment]
https://github.com/HCAWN/gcal-multical-event-merge
https://chrome.google.com/webstore/detail/cal-merge-for-google-cale/dchpdbljalbfnelbfbgncfidhjoibkah?hl=en

Please try my fork. Events that merge now have multiple "click zones" so if you click each colour the respective event window opens:
![image](https://user-images.githubusercontent.com/40216444/187959449-ba6bd68a-29ed-441d-bc56-5e8726f0b9ce.png)

**Comment by aurosharman** [comment]
Has the fork only been released on Chrome, or is it also available on Firefox?  (I'd be willing to take a look at this and see how it works, but I generally browse in Firefox.)

**Comment by HCAWN** [comment]
Sadly I've not got around to publishing in Firefox. Please make an issue to request that so I can have it all in one place. Likewise let me know if it does solve your issue anyway.
H
