### ISSUE TITLE
Month view: Blank Line After Merge

### ISSUE THREAD

**Issue by jbensley** [imightbeamy/gcal-multical-event-merge#8]
Love the feature / plugin, but I am noticing that sometimes merged events still take up the same amount of space in the month view, with a second blank line appearing below the merge. 

Market version as of 2015/03/14

**Comment by imightbeamy** [comment]
Hi, thanks for pointing this out. Unfortunately since this is a chrome extention, and not an actual change to gcal, there's not much to be done about it that without adding a lot of complication. :/ One thing that makes it a little better is using the 3 week view instead, so there's more space in each square.
